In [12]:
print("Welcome to pandas ")

Welcome to pandas

In [8]:
import numpy as np
import pandas as pd

my_df={
    "name":["Alice", "Bob", "Charlie", "Diana"],
    "age": [25, 30, 35, 40],
    "city":["New York", "Paris", "London", "Tokyo"],
    "score":[85, 90, 95, 88]
}
pd_dataframe=pd.DataFrame(my_df)
print(pd_dataframe)

      name  age      city  score
0    Alice   25  New York     85
1      Bob   30     Paris     90
2  Charlie   35    London     95
3    Diana   40     Tokyo     88

In [9]:
pd_dataframe.head(2)

    name  age      city  score
0  Alice   25  New York     85
1    Bob   30     Paris     90

In [10]:
pd_dataframe.tail(2)

      name  age    city  score
2  Charlie   35  London     95
3    Diana   40   Tokyo     88

In [11]:
pd_dataframe.to_csv("pandas_csv")
# if u want to read the csv files then
read_csv=pd.read_csv('pandas_csv')
print("Reading the csv")
print(read_csv)
print("\n\n")
#if u want to exclude the index while exporting the data to excel
exclude_index=pd_dataframe.to_csv("pandas_after_excluding_index_csv",index=False)
print("dataframe after excluding the index is ")


# reading the dataframe after excluding the index
read_csv_after_exclude=pd.read_csv('pandas_csv')
print(read_csv_after_exclude)

Reading the csv
   Unnamed: 0     name  age      city  score
0           0    Alice   25  New York     85
1           1      Bob   30     Paris     90
2           2  Charlie   35    London     95
3           3    Diana   40     Tokyo     88



dataframe after excluding the index is
   Unnamed: 0     name  age      city  score
0           0    Alice   25  New York     85
1           1      Bob   30     Paris     90
2           2  Charlie   35    London     95
3           3    Diana   40     Tokyo     88