In [1]:
import pandas as pd
employees = {
    "Name": ["Alice", "Bob", "Charlie", "Diana"],
    "Age": [28, 34, 25, 40],
    "Department": ["HR", "Engineering", "Marketing", "Finance"],
    "Salary": [50000, 75000, 48000, 90000]
}

pd_dataframe=pd.DataFrame(employees)
pd_dataframe.head(2)

# pd describe will look for the numerical values from the given dataset and perform the operations such as the count,mean,standard deviation on that numerical values and prints the output

pd_dataframe.describe()
# 	    Age	        Salary
# count	4.000000	4.000000
# mean	31.750000	65750.000000
# std	6.652067	20303.940504
# min	25.000000	48000.000000
# 25%	27.250000	49500.000000
# 50%	31.000000	62500.000000
# 75%	35.500000	78750.000000
# max	40.000000	90000.000000

# =============================================================================================================================

train_details=pd.read_csv('train_details.csv')
train_details.head(10)

# you can modify the records of the train_details by using the index
# target the columnwhich u want tomodify specifiy the row and its changed value when u print you will be getting the modified changed value
train_details['speed'][0]=200

# 
train_details

C:\Users\GodwinV\AppData\Local\Temp\ipykernel_25504\2003829514.py:32: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  train_details['speed'][0]=200
C:\Users\GodwinV\AppData\Local\Temp\ipykernel_25504\2003829514.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_details['speed'][0]=200

  trainno  speed       city  distance
0   T1001    200     Mumbai       500
1   T1002    110      Delhi       450
2   T1003    130  Bangalore       600
3   T1004     95    Chennai       350
4   T1005    105    Kolkata       480
5   T1006    115  Hyderabad       520
6   T1007    100  Ahmedabad       400
7   T1008    125       Pune       550
8   T1009     90     Jaipur       300
9   T1010    140    Lucknow       650

In [2]:
# you can give different index instead of 0,1,2.....9
train_details.index=["first","second","third","fourth","fifth","sixth","seventh","eighth","ninth","tenth"]

# pritig the traindetails after modifying index
train_details

        trainno  speed       city  distance
first     T1001    200     Mumbai       500
second    T1002    110      Delhi       450
third     T1003    130  Bangalore       600
fourth    T1004     95    Chennai       350
fifth     T1005    105    Kolkata       480
sixth     T1006    115  Hyderabad       520
seventh   T1007    100  Ahmedabad       400
eighth    T1008    125       Pune       550
ninth     T1009     90     Jaipur       300
tenth     T1010    140    Lucknow       650

In [ ]:
train_data=pd.read_csv('train_details.csv')
train_data

# if any row contains the Nan to drop those rows use 
train_data.dropna()

  trainno  speed       city  distance
0   T1001    120     Mumbai       500
2   T1003    130  Bangalore       600
3   T1004     95    Chennai       350
4   T1005    105    Kolkata       480
5   T1006    115  Hyderabad       520
6   T1007    100  Ahmedabad       400
7   T1008    125       Pune       550
8   T1009     90     Jaipur       300

In [14]:
# to reset the index after removing the empty rows 
train_data.dropna().reset_index()

   index trainno  speed       city  distance
0      0   T1001    120     Mumbai       500
1      2   T1003    130  Bangalore       600
2      3   T1004     95    Chennai       350
3      4   T1005    105    Kolkata       480
4      5   T1006    115  Hyderabad       520
5      6   T1007    100  Ahmedabad       400
6      7   T1008    125       Pune       550
7      8   T1009     90     Jaipur       300