In [5]:
import pandas as pd
import numpy as np
# creating a series 
pd_series=pd.Series(np.arange(1,100))
# to print the datatype of the pdseries
print("pd series datatype",pd_series.dtypes)
print(pd_series)

# to print the type of pdseries
type(pd_series)
# pandas.core.series.Series

pd series datatype int64
0      1
1      2
2      3
3      4
4      5
      ..
94    95
95    96
96    97
97    98
98    99
Length: 99, dtype: int64

pandas.core.series.Series

In [6]:
my_custom_dataframe=pd.DataFrame(np.random.rand(300,5),index=np.arange(300))
print("my dataframe ")
my_custom_dataframe


# dataframe.T transpose the row-> column and column-> row
my_custom_dataframe.T

my dataframe

,0,1,2,3,4,5,6,7,8,9,...,290,291,292,293,294,295,296,297,298,299
0,0.370545,0.113541,0.498292,0.920560,0.318476,0.508915,0.722579,0.044878,0.019192,0.578283,...,0.080697,0.435177,0.171671,0.208424,0.074937,0.884169,0.227594,0.942649,0.106979,0.716835
1,0.152985,0.224123,0.526771,0.784024,0.657789,0.966579,0.339420,0.129808,0.801895,0.363942,...,0.817545,0.134330,0.016965,0.878800,0.403804,0.058497,0.423601,0.515159,0.155482,0.799490
2,0.812716,0.006069,0.665178,0.660241,0.335287,0.792363,0.074646,0.269789,0.677937,0.154794,...,0.248212,0.425653,0.680792,0.206925,0.769471,0.696667,0.438586,0.230143,0.794437,0.785672
3,0.020469,0.290576,0.191801,0.932431,0.214929,0.719608,0.528225,0.825856,0.398021,0.405731,...,0.626976,0.635172,0.377551,0.868688,0.638284,0.344047,0.526754,0.131213,0.343410,0.279900
4,0.414206,0.957472,0.159301,0.815439,0.399165,0.994626,0.039533,0.178195,0.942656,0.216478,...,0.612124,0.160223,0.081639,0.786027,0.233948,0.179643,0.410789,0.639101,0.289310,0.563328

In [7]:
my_custom_dataframe.head()

          0         1         2         3         4
0  0.370545  0.152985  0.812716  0.020469  0.414206
1  0.113541  0.224123  0.006069  0.290576  0.957472
2  0.498292  0.526771  0.665178  0.191801  0.159301
3  0.920560  0.784024  0.660241  0.932431  0.815439
4  0.318476  0.657789  0.335287  0.214929  0.399165

In [8]:
# to find the datatype of dataframe
my_custom_dataframe.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [9]:
my_custom_dataframe[0][0]="godwin"
my_custom_dataframe.dtypes

# if u convert the any one row of the column entire datatype of the column will be changed

C:\Users\GodwinV\AppData\Local\Temp\ipykernel_28372\2327260318.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  my_custom_dataframe[0][0]="godwin"
C:\Users\GodwinV\AppData\Local\Temp\ipykernel_28372\2327260318.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'godwin' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  my_custom_dataframe[0][0]="godwin"

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [10]:
# tosort the dataframe
# sort ascending with horizontal axis
my_custom_dataframe.sort_index(axis=0,ascending=True)

# sort descending with vertical axis
my_custom_dataframe.sort_index(axis=1,ascending=False).head()

          4         3         2         1         0
0  0.414206  0.020469  0.812716  0.152985    godwin
1  0.957472  0.290576  0.006069  0.224123  0.113541
2  0.159301  0.191801  0.665178  0.526771  0.498292
3  0.815439  0.932431  0.660241  0.784024   0.92056
4  0.399165  0.214929  0.335287  0.657789  0.318476

In [11]:
copying_dataframe=my_custom_dataframe
copying_dataframe

            0         1         2         3         4
0      godwin  0.152985  0.812716  0.020469  0.414206
1    0.113541  0.224123  0.006069  0.290576  0.957472
2    0.498292  0.526771  0.665178  0.191801  0.159301
3     0.92056  0.784024  0.660241  0.932431  0.815439
4    0.318476  0.657789  0.335287  0.214929  0.399165
..        ...       ...       ...       ...       ...
295  0.884169  0.058497  0.696667  0.344047  0.179643
296  0.227594  0.423601  0.438586  0.526754  0.410789
297  0.942649  0.515159  0.230143  0.131213  0.639101
298  0.106979  0.155482  0.794437  0.343410  0.289310
299  0.716835  0.799490  0.785672  0.279900  0.563328

[300 rows x 5 columns]

In [17]:
copying_dataframe[0][0]="roshan"
# note if u try to copy the dataframe like this internally both the dataframes are pointing to the same memory location so changes done in the copied dataframe will also be reflected in the original dataframe
# copying_dataframe 
my_custom_dataframe

C:\Users\GodwinV\AppData\Local\Temp\ipykernel_28372\628798867.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  copying_dataframe[0][0]="roshan"
C:\Users\GodwinV\AppData\Local\Temp\ipykernel_28372\628798867.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  copying_dataframe[0][0]="roshan"

            0         1         2         3         4
0      roshan  0.152985  0.812716  0.020469  0.414206
1    0.113541  0.224123  0.006069  0.290576  0.957472
2    0.498292  0.526771  0.665178  0.191801  0.159301
3     0.92056  0.784024  0.660241  0.932431  0.815439
4    0.318476  0.657789  0.335287  0.214929  0.399165
..        ...       ...       ...       ...       ...
295  0.884169  0.058497  0.696667  0.344047  0.179643
296  0.227594  0.423601  0.438586  0.526754  0.410789
297  0.942649  0.515159  0.230143  0.131213  0.639101
298  0.106979  0.155482  0.794437  0.343410  0.289310
299  0.716835  0.799490  0.785672  0.279900  0.563328

[300 rows x 5 columns]

In [24]:
# copying the dataframe without modifying the original data
new_copy2=my_custom_dataframe.copy()
print(new_copy2)

new_copy2[0][0]="roshan"
print("dataframe after modifying ")
print(new_copy2)

print("original dataframe ")
print(my_custom_dataframe)

            0         1         2         3         4
0      godwin  0.152985  0.812716  0.020469  0.414206
1    0.113541  0.224123  0.006069  0.290576  0.957472
2    0.498292  0.526771  0.665178  0.191801  0.159301
3     0.92056  0.784024  0.660241  0.932431  0.815439
4    0.318476  0.657789  0.335287  0.214929  0.399165
..        ...       ...       ...       ...       ...
295  0.884169  0.058497  0.696667  0.344047  0.179643
296  0.227594  0.423601  0.438586  0.526754  0.410789
297  0.942649  0.515159  0.230143  0.131213  0.639101
298  0.106979  0.155482  0.794437  0.343410  0.289310
299  0.716835  0.799490  0.785672  0.279900  0.563328

[300 rows x 5 columns]
dataframe after modifying
            0         1         2         3         4
0      roshan  0.152985  0.812716  0.020469  0.414206
1    0.113541  0.224123  0.006069  0.290576  0.957472
2    0.498292  0.526771  0.665178  0.191801  0.159301
3     0.92056  0.784024  0.660241  0.932431  0.815439
4    0.318476  0.657789  0.335287  0.214929  0.399165
..        ...       ...       ...       ...       ...
295  0.884169  0.058497  0.696667  0.344047  0.179643
296  0.227594  0.423601  0.438586  0.526754  0.410789
297  0.942649  0.515159  0.230143  0.131213  0.639101
298  0.106979  0.155482  0.794437  0.343410  0.289310
299  0.716835  0.799490  0.785672  0.279900  0.563328

[300 rows x 5 columns]
original dataframe
            0         1         2         3         4
0      godwin  0.152985  0.812716  0.020469  0.414206
1    0.113541  0.224123  0.006069  0.290576  0.957472
2    0.498292  0.526771  0.665178  0.191801  0.159301
3     0.92056  0.784024  0.660241  0.932431  0.815439
4    0.318476  0.657789  0.335287  0.214929  0.399165
..        ...       ...       ...       ...       ...
295  0.884169  0.058497  0.696667  0.344047  0.179643
296  0.227594  0.423601  0.438586  0.526754  0.410789
297  0.942649  0.515159  0.230143  0.131213  0.639101
298  0.106979  0.155482  0.794437  0.343410  0.289310
299  0.716835  0.799490  0.785672  0.279900  0.563328

[300 rows x 5 columns]

C:\Users\GodwinV\AppData\Local\Temp\ipykernel_28372\2721951097.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  new_copy2[0][0]="roshan"
C:\Users\GodwinV\AppData\Local\Temp\ipykernel_28372\2721951097.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_copy2[0][0]="roshan"

In [27]:
# To avoid issues with shallow copying and also the SettingWithCopyWarning, use the command below.
# .loc stands for "location" and is used for label-based indexing to safely assign values.
# This is the recommended way for modifying DataFrame values.
copying_dataframe.loc[0,0]="god"
copying_dataframe

            0         1         2         3         4
0         god  0.152985  0.812716  0.020469  0.414206
1    0.113541  0.224123  0.006069  0.290576  0.957472
2    0.498292  0.526771  0.665178  0.191801  0.159301
3     0.92056  0.784024  0.660241  0.932431  0.815439
4    0.318476  0.657789  0.335287  0.214929  0.399165
..        ...       ...       ...       ...       ...
295  0.884169  0.058497  0.696667  0.344047  0.179643
296  0.227594  0.423601  0.438586  0.526754  0.410789
297  0.942649  0.515159  0.230143  0.131213  0.639101
298  0.106979  0.155482  0.794437  0.343410  0.289310
299  0.716835  0.799490  0.785672  0.279900  0.563328

[300 rows x 5 columns]

In [ ]:
# drops the entire column 
copying_dataframe.drop(0,axis=1)

            1         2         3
0    0.152985  0.812716  0.020469
1    0.224123  0.006069  0.290576
2    0.526771  0.665178  0.191801
3    0.784024  0.660241  0.932431
4    0.657789  0.335287  0.214929
..        ...       ...       ...
295  0.058497  0.696667  0.344047
296  0.423601  0.438586  0.526754
297  0.515159  0.230143  0.131213
298  0.155482  0.794437  0.343410
299  0.799490  0.785672  0.279900

[300 rows x 3 columns]